version: '3.1'

# Docker Services

services:

  # PHP/Apache Service
  
  apirest:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: postventa-api-rest
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./app/:/var/www/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - nb-api-rest-network
  
# Docker Networks

networks:
  postventa-api-rest-network:
    driver: bridge
